project:
  type: website

website:
  title: "Exploring Data Science"
  description: "Learning, practicing, and mastering the art of data science."
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Luke-Rutten
      - icon: linkedin
        href: https://www.linkedin.com/in/lukerutten/
format:
  html:
    theme: lux
    css: styles.css

editor: visual

